[workspace]
resolver = "2"
members = [
    "position_extractor",
    "compact_board",
    "trie_farmer",
    "trie_trimmer",
    "fish_teacher",
    "tch_tchotchkes",
    "web_api",
    "web_types",
]
exclude = [
    "nn-chess-frontend",
]