[package]
name = "compact_board"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitreader = "0.3.8"
bitvec = "1.0.1"
shakmaty = "0.26.0"
